[extend]
# This path must match where you copied the central config in the step above
path = "./Rules/gitleaks.toml"

[allowlist]
description = "Repo specific ignores"
paths = [
      '''/test/'''
      '''/python-script-for-gitleaks.py'''
      '''/dont_scan/'''
]
